import {hamster} from './art.js?v=09c0f56a41bdf7e7';
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {rareBalance} from './economy.js?v=09c0f56a41bdf7e7';
export function carePanel(world){const c=world.care;if(!c)return '';const ham=c.active?c.hams[c.active]:null,stars=rareBalance(world),ghosts=Object.values(c.hams).filter(h=>h.state==='ghost');
 const feeling=c.enabled===false?'お世話はお好みで。始めるまで時間は進みません。':c.paused?'いまは、おやすみ中。時間は進みません。':ham?.state==='sulking'?'少し、すねているみたい。':ham?'今日も、いつもの場所で。':'お空に、小さな思い出が残りました。';
 return `<section class="care-panel"><div class="care-heading"><strong>${ham?escapeText(ham.name):'お空の思い出'}</strong><span>☆ ${stars} 星のかけら</span></div><p>${feeling}</p>${ham?`<div class="care-actions"><button id="care-feed" ${c.paused?'disabled':''}>ごはん</button><button id="care-clean" ${c.paused?'disabled':''}>おそうじ</button></div><button id="care-pause" class="care-link">${c.enabled===false?'お世話を始める（任意）':c.paused?'おやすみから戻る':'長く休むときは、おやすみへ'}</button>`:`<button id="care-welcome" class="primary wide">新しい子を迎える</button>${ghosts.length?`<label class="sky-select">また会いたい子 <select id="care-ghost">${ghosts.map(h=>`<option value="${h.id}">${escapeText(h.name)}</option>`).join('')}</select></label><button id="care-revive" class="secondary wide" ${stars<3?'disabled':''}>星のかけら3つで、また一緒に</button>`:''}`}
 <details><summary>お世話と、お空の記録</summary><p>お世話は任意です。始めるまでは時間が進みません。ごはんとおそうじは無料です。お世話をしなくてもパズルや家具はそのまま。仮設定では48時間で寂しそうになり、14日でお空へ旅立ちます。おやすみ中は進みません。</p><p>日替わりを好きな難度で3問クリアすると、1日1つ星のかけらが届きます。3つで、前の子の個性と記録を保ったまま再会できます。今いる子との暮らしが終わった後に選べます。</p>${c.memories.map(m=>`<span class="sky-memory">☁ ${escapeText(c.hams[m.id].name)}との思い出</span>`).join('')||'<p>思い出は、これから少しずつ。</p>'}</details></section>`;
}
export const hatchMarkup=()=>`<section class="hatch-scene" aria-label="新しいハムのお迎え"><p>こんにちは。ここが、ぼくのおうち？</p><svg viewBox="0 0 200 200" aria-hidden="true"><ellipse cx="100" cy="171" rx="64" ry="11" fill="#B6B99C55"/><g class="egg-baby"><svg x="53" y="38" width="94" height="94" viewBox="0 0 120 120">${hamster('joy').replace(/^<svg[^>]*>|<\/svg>$/g,'')}</svg></g><g class="egg-top"><path d="M44 104C47 17 153 17 156 104l-17-10-20 14-19-14-21 14-18-14Z" fill="#FFF1CD" stroke="#AC956E" stroke-width="3"/><ellipse cx="77" cy="62" rx="9" ry="13" fill="#E4C99B"/></g><g class="egg-bottom"><path d="m44 104 17-10 18 14 21-14 19 14 20-14 17 10q-2 68-56 68t-56-68Z" fill="#FFF1CD" stroke="#AC956E" stroke-width="3"/></g></svg><button id="hatch-skip" class="secondary">おうちへ</button></section>`;
