import {coinIcon} from './coin-ui.js?v=09c0f56a41bdf7e7';
import {animateHome} from './home-motion.js?v=09c0f56a41bdf7e7';
import {carePanel,hatchMarkup} from './care-ui.js?v=09c0f56a41bdf7e7';
import {balance,openDay,buy,place,removePlacement,LEGACY_SLOTS,TEST_BALANCE,tickResident,tendResident,restResident,welcomeResident,returnResident} from './economy.js?v=09c0f56a41bdf7e7';
import {localDate,LEVELS} from './daily.js?v=09c0f56a41bdf7e7';import {SHOP,ROOMS,SLOT_LABELS} from './home-catalog.js?v=09c0f56a41bdf7e7';import {homeScene,shopArt} from './home-art.js?v=09c0f56a41bdf7e7';import {furniture,furnitureArt} from './art.js?v=09c0f56a41bdf7e7';
const names={easy:'やさしい',standard:'ふつう',hard:'むずかしい'};
export function mountWorld({store,catalog,onDaily,onClose}){
 const dialog=document.createElement('dialog');dialog.id='world-dialog';dialog.setAttribute('aria-label','ハムのおうちと日替わり');document.body.append(dialog);
 let stopMotion=()=>{};dialog.addEventListener('close',()=>stopMotion());
 let tab='home',room='main',level='easy',selection=null,slot=null,state=null,busy=false,notice='',inventoryOpen=false,hatchPending=false;
 const el=id=>dialog.querySelector('#'+id);
 const allItems=()=>[...state.ownedLegacy.map(id=>{const i=Number(id.slice(7));return {id,name:furniture[i].name,description:furniture[i].note,kind:'furniture',slots:[LEGACY_SLOTS[i]],legacy:true};}),...SHOP.items];
 const owned=id=>state.ownedLegacy.includes(id)||Object.hasOwn(state.purchases,id);
 const transact=async fn=>{state=await store.transact(fn);};
 async function run(fn){if(busy)return;busy=true;try{await fn();}catch(error){notice=({INSUFFICIENT_COINS:'コインが足りません。日替わりやパズルで少しずつ集めよう。',REQUIRES_UNLOCK:'先にガラス屋根の庭を広げると購入できます。',INVALID_SLOT:'この場所には置けません。',INCOMPATIBLE_SLOT:'この家具に合う場所を選んでください。'}[error.message]||'保存できませんでした。データを消さずに、もう一度お試しください。');}finally{busy=false;render();if(hatchPending){hatchPending=false;dialog.querySelector('.world-shell').insertAdjacentHTML('beforeend',hatchMarkup());const dismiss=()=>dialog.querySelector('.hatch-scene')?.remove();el('hatch-skip').onclick=dismiss;setTimeout(dismiss,matchMedia('(prefers-reduced-motion: reduce)').matches?300:2200);}}}
 function render(){stopMotion();if(!state)return;const amount=balance(state),item=allItems().find(i=>i.id===selection),today=localDate();
  dialog.innerHTML=`<div class="world-shell"><header class="world-header"><div><small>HAMUDOKU HOME</small><h2>${tab==='daily'?'きょうのひらめき':tab==='shop'?'おうちの道具店':'ぼくの、特等席。'}</h2></div><span class="wallet" aria-label="所持コイン ${amount}">${coinIcon()} ${amount}</span><button id="world-close" aria-label="閉じる">×</button></header><nav class="world-tabs" aria-label="おうちメニュー">${[['home','おうち'],['daily','日替わり'],['shop','ショップ']].map(([id,label])=>`<button data-tab="${id}" aria-current="${tab===id?'page':'false'}">${label}</button>`).join('')}</nav><div class="world-scroll" id="world-content"></div><p class="world-notice" id="world-notice" role="status">${notice||'ひらめきを、暮らしのひとつに。'}</p></div>`;
  el('world-close').onclick=()=>{stopMotion();dialog.close();onClose?.();};dialog.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>run(async()=>{tab=b.dataset.tab;selection=null;notice='';if(tab==='daily')await transact(w=>openDay(w,localDate(),catalog));}));
  const content=el('world-content');
  if(tab==='daily'){
   const day=state.days[today];if(!day){content.innerHTML='<button id="new-day" class="primary wide">きょうの問題を開く</button>';el('new-day').onclick=()=>run(()=>transact(w=>openDay(w,today,catalog)));return;}
   const count=day.puzzles.filter(p=>state.dailyClaims[p.id]).length;
   content.innerHTML=`<section class="daily-intro"><span>${today.replaceAll('-',' / ')}</span><h3>今日は、どの気分？</h3><p>3つの難しさから、好きなものを。<br>各3問。クリアするとコインが届きます。</p><strong>${count} / 9 問クリア</strong></section><div class="difficulty-tabs">${LEVELS.map(l=>`<button data-level="${l}" aria-pressed="${l===level}">${names[l]}</button>`).join('')}</div><div class="daily-cards">${day.puzzles.filter(p=>p.level===level).map(p=>{const claimed=!!state.dailyClaims[p.id],marked=p.game.marks.some(x=>x);return `<button class="daily-card" data-daily="${p.id}"><span class="daily-number">${p.slot+1}</span><span><strong>第${p.slot+1}問</strong><small>${claimed?'クリア済み · もう一度':marked?'途中からつづける':p.game.board.n+' × '+p.game.board.n+' のおへや'}</small></span><b class="daily-prize">${claimed?'<span class="received-check">✓ 受取済み</span>':coinIcon()+'<span>'+TEST_BALANCE.daily[level]+'</span>'}</b></button>`;}).join('')}</div><p class="world-fine">好きな難度の3問で、1日1つ星のかけらも届きます。<br>コインは各問題の初回クリアで受け取れます。<br>日付が変わっても、受け取った記録は残ります。</p>`;
   dialog.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;render();});dialog.querySelectorAll('[data-daily]').forEach(b=>b.onclick=()=>run(async()=>{const p=state.days[today].puzzles.find(p=>p.id===b.dataset.daily);dialog.close();await onDaily(p,!!state.dailyClaims[p.id]);}));return;
  }
  const roomOptions=ROOMS.map(r=>`<button data-room="${r.id}" aria-pressed="${room===r.id}" ${!state.rooms.includes(r.id)?'class="locked-room"':''}>${r.name}${state.rooms.includes(r.id)?'':' ＋'}</button>`).join('');
  let preview=item?.kind==='furniture'?{...item,slots:[slot||item.slots[0]]}:null;let shownRoom=item?.kind==='expansion'?item.roomId:room;
  content.innerHTML=`<div class="room-selector" aria-label="部屋を選ぶ">${roomOptions}</div><div class="home-canvas ${preview||item?.kind==='expansion'?'is-preview':''}">${homeScene(state,shownRoom,preview)}${preview||item?.kind==='expansion'?'<span class="preview-label">置いたイメージ · まだ変更していません</span>':''}</div><p class="home-caption">${item?item.description:'ぼくの席、少しずつ広くなってきたね。'}</p><div id="world-tools"></div>`;
  dialog.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const id=b.dataset.room;if(!state.rooms.includes(id)){tab='shop';selection=SHOP.items.find(i=>i.roomId===id).id;}else{room=id;selection=null;}slot=null;render();});
  stopMotion=animateHome(content.querySelector('.home-scene'));
  const tools=el('world-tools');
  if(tab==='shop'){
   if(!item){selection=SHOP.items[0].id;render();return;}
   const isOwned=owned(item.id),need=item.requires?.some(id=>!state.rooms.includes(id)),affordable=amount>=item.price;
   tools.innerHTML=`<section class="shop-choice"><div><small>${item.kind==='expansion'?'おうちを広げる':'ハムの暮らしが変わる家具'}</small><h3>${item.name}</h3><p>${isOwned?'持っています':coinIcon()+'<strong>'+item.price+'</strong> コイン'}</p></div><button id="shop-buy" class="primary" ${isOwned||need||!affordable?'disabled':''}>${isOwned?'購入済み':need?'庭の拡張が必要':!affordable?'あと '+(item.price-amount)+' コイン':item.price+' コインで購入'}</button>${isOwned&&item.kind==='furniture'?'<button id="shop-place" class="secondary">おうちに置く</button>':''}</section><div class="shop-cards">${SHOP.items.map(i=>`<button class="shop-card ${selection===i.id?'selected':''}" data-item="${i.id}">${shopArt(i.id)}<strong>${i.name}</strong><small>${owned(i.id)?'所持済み':coinIcon()+i.price}</small></button>`).join('')}</div><p class="world-fine">日替わりの全9問で135コイン。通常クリアでも3コイン。<br>広告視聴や支払いは必要ありません。</p>`;
   el('shop-buy').onclick=()=>run(async()=>{await transact(w=>buy(w,item.id,SHOP));notice=item.name+'が届きました。';if(item.kind==='expansion'){room=item.roomId;selection=null;tab='home';} });el('shop-place')?.addEventListener('click',()=>{tab='home';inventoryOpen=true;if(item.requires?.includes('garden'))room='garden';render();});dialog.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selection=b.dataset.item;slot=null;const next=SHOP.items.find(i=>i.id===selection);if(next.requires?.includes('garden'))room='garden';else if(!state.rooms.includes(room))room='main';render();});
  }else{
   const inventory=allItems().filter(i=>i.kind==='furniture'&&owned(i.id));const available=item?.slots?.filter(s=>ROOMS.find(r=>r.id===room).slots.includes(s))||[];if(!available.includes(slot))slot=available[0];
   tools.innerHTML=`${carePanel(state)}${item?`<section class="placement-choice"><h3>${item.name}</h3><label>置く場所 <select id="place-slot">${available.map(s=>`<option value="${s}" ${slot===s?'selected':''}>${SLOT_LABELS[s]}</option>`).join('')}</select></label><div class="actions"><button id="place-item" class="primary" ${!available.length?'disabled':''}>ここに置く</button><button id="preview-cancel" class="secondary">プレビューを閉じる</button></div><small>そこにある家具は引き出しに戻ります。</small></section>`:''}<details class="home-drawer" ${inventoryOpen?'open':''}><summary>家具の引き出し <span>${inventory.length}点</span></summary><div class="inventory-cards">${inventory.map(i=>`<button data-owned="${i.id}">${i.legacy?furnitureArt(Number(i.id.slice(7))):shopArt(i.id)}<strong>${i.name}</strong><small>${Object.values(state.placements).includes(i.id)?'配置中':'引き出し'}</small></button>`).join('')||'<p>パズルをクリアすると、最初の家具が届きます。</p>'}</div></details><details class="home-drawer"><summary>配置中の家具をしまう</summary><div class="placed-list">${Object.entries(state.placements).filter(([k])=>k.startsWith(room+'/')).map(([k,id])=>`<button data-remove="${k.split('/')[1]}">${allItems().find(i=>i.id===id)?.name||id}をしまう</button>`).join('')||'<p>まだ家具を置いていません。</p>'}</div></details><button id="visit-shop" class="secondary wide">道具店をのぞく</button>`;
   el('care-feed')?.addEventListener('click',()=>run(async()=>{await transact(w=>tendResident(w,'feed',Date.now()));notice='もぐもぐ。ここで食べると、おいしいね。';}));
   el('care-clean')?.addEventListener('click',()=>run(async()=>{await transact(w=>tendResident(w,'clean',Date.now()));notice='すっきり。いつもの席で、のんびり。';}));
   el('care-pause')?.addEventListener('click',()=>run(async()=>{await transact(w=>restResident(w,!w.care.paused,Date.now()));notice=state.care.paused?'おやすみ中は、お世話の時間が止まります。':'おかえり。ゆっくり始めよう。';}));
   el('care-welcome')?.addEventListener('click',()=>run(async()=>{await transact(w=>welcomeResident(w,Date.now()));notice='新しい暮らしが始まります。';hatchPending=true;}));
   el('care-revive')?.addEventListener('click',()=>run(async()=>{const id=el('care-ghost').value;await transact(w=>returnResident(w,id,Date.now()));notice='おかえり。また、いつもの席へ。';hatchPending=true;}));
   el('visit-shop').onclick=()=>{tab='shop';selection=null;render();};dialog.querySelector('.home-drawer').ontoggle=e=>{inventoryOpen=e.target.open;};dialog.querySelectorAll('[data-owned]').forEach(b=>b.onclick=()=>{selection=b.dataset.owned;slot=null;inventoryOpen=true;render();});
   if(item){el('place-slot').onchange=e=>{slot=e.target.value;render();};el('preview-cancel').onclick=()=>{selection=null;render();};el('place-item').onclick=()=>run(async()=>{await transact(w=>place(w,item.id,room,slot,SHOP));selection=null;notice='お部屋に置きました。ハムも気に入ったみたい。';});}
   dialog.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>run(async()=>{await transact(w=>removePlacement(w,room,b.dataset.remove));notice='引き出しに戻しました。';}));
  }
 }
 return {async open(next='home',message=''){tab=next;selection=null;notice=message;await run(async()=>{await transact(w=>{const live=tickResident(w,Date.now());return next==='daily'?openDay(live,localDate(),catalog):live;});if(!dialog.open)dialog.showModal();});},async dailyDone(message){await this.open('daily',message);},close(){stopMotion();dialog.close();}};
}
